### ISSUE TITLE
[Bug]: Hyprland high cpu usage

### ISSUE THREAD

**Issue by maykel535** [prasanthrangan/hyprdots#1019]
### Description

I've installed arch vanilla, nothing more.

Launch this excited script and all ok, except the process hyprland ... The CPU usage is very high

Attach screenshot

![240305_17h23m57s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/3702872/eabc06dd-b206-456c-a104-39929bf936bf)

**Comment by kRHYME7** [comment]
Try to run ``` Hyprdots power save -ba ``` see if anything changes

**Comment by maykel535** [comment]
ok, at the moment the CPU is ok with this command that add:

source = /home/maykel/.cache/hyprdots-ctl/power_manager.conf #! This File is modified by Hyprdots-ctl power options(To remove: 'Hyprdots power reset')

Content:

animation = borderangle, 0

**Comment by kRHYME7** [comment]
This is actually a Hyprland issue. The borderangle animation consumes  a lot of power. You can raise this issue in Hyprland.Or you can disable borderangle animation totally

**Comment by kRHYME7** [comment]
This is actually a Hyprland issue. The borderangle animation consumes  a lot of power. You can raise this issue in Hyprland.Or you can disable borderangle animation totally by adding this command ``` animation = borderangle , 0 ``` inside   the ``` ./userprefs.conf ```


I'll be closing this as #641 already raised this issue here. Thank you. Feel free to ask something.
