### ISSUE TITLE
Screen app flickering

### ISSUE THREAD

**Issue by hui3215** [prasanthrangan/hyprdots#115]
Hello, when I use some software (such as a file manager), I operate it, and there will be a splash screen, how should I solve it

**Comment by prasanthrangan** [comment]
Hi, what splash screen? can you please share a screenshot?

**Comment by Kemipso** [comment]
Hey,


I'm just a user on this project, but as far as I know there is no splash screen included in any theme in these dots, except for the Hyprland splash screen (on launch of Hyprland itself).
If you mean that, then you can disable it in your user preferences file, under ~/.config/hypr/userprefs.conf
Create (or edit) the misc category, and include:
```
misc {
    disable_splash_rendering = true
}
```

You can find all variables for Hyprland on https://wiki.hyprland.org/Configuring/Variables/#misc

**Comment by 2420228300** [comment]
> Hi, what splash screen? can you please share a screenshot?

Hello, the screen application is flashing, I want to give you screenshots or screen recording to provide effective help, but when I take screenshots can not be taken in time, this outrageous problem when recording the screen actually disappeared. So I'm going to describe this phenomenon in general now, which is that when you enter a folder when you open the file manager, the app will flicker, but it will not flicker after mouse movement. I installed the system using the previous script did not have this problem, since using the latest script

**Comment by prasanthrangan** [comment]
are you using nvidia ? if so please check if nvidia variables are enabled/disabled as mentioned in the [wiki](https://wiki.hyprland.org/Nvidia/)

Also is the VRR enabled? if so, please try disabling it.

**Comment by kRHYME7** [comment]
This Might be resolved as this issue was stale. Please reopen if necessary.
