### ISSUE TITLE
[Feature Request]: Follow system locales for screenshot directory

### ISSUE THREAD

**Issue by dieBakterie** [prasanthrangan/hyprdots#1186]
### Description

Follow the Systems language for Pictures/Screenshot folder. I'm personally fine with an Screenshot folder in my "Bilder" folder.

### Use Case

For people who don't have their system on another language than english to avoid duplicates Pictures.

### Proposed Solution

Use XDG_PICTURES_DIR defined in .config/user-dirs.dirs to follow the systems locale

**Comment by kRHYME7** [comment]
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/8e94011d-290f-4978-8874-2a64b39445f1)

I think it should respect ```  XDG_PICTURES_DIR ```

**Comment by dieBakterie** [comment]
Yeah if you mean set it manually yes. It's not automatically my one and i don't get to use the XDG_PICTURES_DIR. Help appreciated
![grafik](https://github.com/prasanthrangan/hyprdots/assets/50206827/0707588c-258e-47fa-9406-5f41b5189a70)
![grafik](https://github.com/prasanthrangan/hyprdots/assets/50206827/f3bbcbc8-aa69-4659-a6a1-60e2deaed1df)
It's creating an folder Pictures as you can see and i'ts set static in the script. I tried to use the existing one defined in `~/.config/user-dirs.dirs` but don't get it to save there

**Comment by Skerse** [comment]
Oh, it's not respecting XDG_PICTURES_DIR because we're defining XDG_PICTURES_DIR as `$HOME/Pictures` as shown here: 

![Screenshot_20240325-133718_1.png](https://github.com/prasanthrangan/hyprdots/assets/139541046/8bc8902f-c1e6-4db7-befa-49661ad9ef48)

I don't know why it's like that, but i'll see about changing that soon!

**Comment by dieBakterie** [comment]
Thanks

**Comment by Skerse** [comment]
Okay, so a solution i just thought of would be to install [xdg-user-dirs](https://archlinux.org/packages/extra/x86_64/xdg-user-dirs/). After looking at the [Arch Wiki page](https://wiki.archlinux.org/title/XDG_user_directories) i realized you can do something like `xdg-user-dirs PICTURES` and have it output the directory path specified from `~/.config/user-dirs.dirs` which can be easily edited. Maybe we do that? However, we would have to install a separate package.

Another solution could be to source user directory paths from `~/.config/hyprdots/scripts/globalcontrol.sh` so that everything could be specified and edited there too.

@kRHYME7 what do you think?

**Comment by kRHYME7** [comment]
The Screenshot scripts tries to respect the XDG_PICTURES_DIR if the environments had it set.

We might consider decoratively install this package because it is only required by STEAM
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/9e7ab03b-237f-4a31-9a82-93c789f59289)

@Skerse 😄

**Comment by Skerse** [comment]
> The Screenshot scripts will try to respect the XDG_PICTURES_DIR if the environments had it set. The main problem is xdg-user-dir won't set it.

Ah i see, actually this works fine, so if anyone wants to set their own environment variable to overwrite the path given it's pretty easy.

> Can we simplify it by setting an env inside ./userprefs.conf ?

Yeah, i think we can. Maybe add it into the template?

Honestly, this is why we probably should have better documentation in the [Hyprdots Wiki](https://github.com/prasanthrangan/hyprdots/wiki). I and who ever else wants to should do something about that sometime, since this project is getting pretty big.

**Comment by dieBakterie** [comment]
It's Set in `user-dirs.dirs` in `~/.config/` could just ready it from there and set it in the screenshots Script?

**Comment by dieBakterie** [comment]
> It's Set in `user-dirs.dirs` in `~/.config/` could just ready it from there and set it in the screenshots Script?

I'll try this method

**Comment by kRHYME7** [comment]
add ``` env = XDG_PICTURES_DIR,"$HOME/prefered_directory" ```  to your ``` ~/.config/hypr/userprefs.conf ```

What I meant is you can add the ENV variables on the hyprland configuration  this way we dont need to install another software. 

+ Problem with ``` xdg-user-dir ``` is it is not respected and not  run on startup. (unless you're on gnome? )  It needs a systemd service to auto start when user logs in.

**Comment by dieBakterie** [comment]
Yeah what i meant was read IT out from the File user-dirs.dirs and save IT in the variable

**Comment by dieBakterie** [comment]
> add `env = XDG_PICTURES_DIR,"$HOME/prefered_directory"` to your `~/.config/hypr/userprefs.conf`
> 
> What I meant is you can add the ENV variables on the hyprland configuration this way we dont need to install another software.
> 
And in the script i need to comment out the if statement which sets the XDG_PICTURES_DIR to /$home/Pictures if yes then it doesn't works for me.

**Comment by dieBakterie** [comment]
I don't get it to use the one defined in `userprefs.conf`

**Comment by dieBakterie** [comment]
Ok thanks for the info

**Comment by dieBakterie** [comment]
![grafik](https://github.com/prasanthrangan/hyprdots/assets/50206827/d7a0c8bd-a131-4db6-b9dd-e65f6160f3de)
![grafik](https://github.com/prasanthrangan/hyprdots/assets/50206827/1b717f72-6e0e-438a-ad02-a8162a8f0b0c)
![grafik](https://github.com/prasanthrangan/hyprdots/assets/50206827/a515849b-7ce3-48b5-b768-f7c75407f3f6)
I think without the quotes it should work

**Comment by dieBakterie** [comment]
why is it creating those folders?

**Comment by kRHYME7** [comment]
what's your ``` env | grep LANG ``` ?

**Comment by dieBakterie** [comment]
`LANG=de_DE.UTF-8` and when i comment Out the Fallback If Statement it works else IT doesn't and the notification stopped working too

**Comment by dieBakterie** [comment]
If i do the keykomb for Screenshot it creates these weird folders `"/home/bakterie/Bilder"/Screenshot`

**Comment by kRHYME7** [comment]
My bad please remove the " " 

should be 
```
env = XDG_PICTURES_DIR,$HOME/prefered_directory
```

What is the output for  ``` env | grep PICTURES ``` ? 

Remember if you want to change "ENVs" you need to reboot or relogin

**Comment by dieBakterie** [comment]
It's `/home/Bakterie/Bilder`

**Comment by dieBakterie** [comment]
No refactor needed my bad

**Comment by kRHYME7** [comment]
```  env = XDG_PICTURES_DIR,$HOME/Bilder ```

Does this work?

**Comment by dieBakterie** [comment]
Yeah and notifications too let me Check real quick If i've commented Out the Fallback one and what If it's not

**Comment by dieBakterie** [comment]
No need to comment it out anymore

**Comment by dieBakterie** [comment]
this `env = XDG_PICTURES_DIR,$HOME/Bilder` doesnt't work anymore w screenshot.sh under HyDe?!
