### ISSUE TITLE
Update some keybinds 

### ISSUE THREAD

**Issue by Sri-dhar** [prasanthrangan/hyprdots#1403]
update some keybinds in the "keybindings.conf" file
the changes are not reflecting in the system 
is there any update.sh or 
i have to reinstall everything using install.sh?

**Comment by kRHYME7** [comment]
`Hyde restore Config ` the keybindings will be on preserve mode so click OVERWRITE then select what configs to be overwriten.

**Comment by Sri-dhar** [comment]
Can you tell me where is this OVERWRITE Button


[
[reflore@reflore-618 HyDE]$ Hyde restore config
			[Config]        ﬌ Only restores dots from default '${CloneDir}/Configs'
			[Clone]         ﬌ Restores dots from a clone repository. 
						ﯧ Provide ~/path/to/clone/directory
			[BackUp]        ﬌ Restores dots from previous backup.
						  Files might not be complete
						ﯦ You can cherry pick a file/dir from a backup
			[Link]          ﬌ Links a clone directory. Useful if you want to change your CloneDir
[reflore@reflore-618 HyDE]$ 
]

**Comment by kRHYME7** [comment]
https://github.com/kRHYME7/Hyde-cli/wiki/Dots-Management

https://www.youtube.com/watch?v=l3CiiSTpJ78

https://github.com/kRHYME7/Hyde-cli


if you don't want to use the CLI 

1. navigate to your clone directory
2. cd go to scripts
3. edit ` ./restore_cfg.lst ` 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/ed2c205b-272d-4513-8760-bc40c672eb47)
4. Make the line with the with `N|Y ` into `Y|Y ` so that it will be overwritten everytime you run `./install.sh -r `

**Comment by Sri-dhar** [comment]
Thank you so much Bro
For the help and the youtube video
