### ISSUE TITLE
Catpuccin Latte Theme get wrong color on system app

### ISSUE THREAD

**Issue by hoanggbao00** [prasanthrangan/hyprdots#1479]
When no focus: 
![image](https://github.com/prasanthrangan/hyprdots/assets/78465334/d56b1131-2b8e-459e-ae84-7f9bda2fb7ff)

When focus:
![image](https://github.com/prasanthrangan/hyprdots/assets/78465334/8ad2099c-d6bd-4766-b019-c581894b655c)

**Comment by kRHYME7** [comment]
check other themes? only latte?

**Comment by hoanggbao00** [comment]
> check other themes? only latte?

yes, only latte. how can i configure those color?
other themes still look good.

**Comment by kRHYME7** [comment]
I can't really see the problem TBH. Sorry 😅


Try to enable wallbash first maybe you'll like it.

**Comment by hoanggbao00** [comment]
>  I can't really see the problem TBH. Sorry 😅
> 
> 
> Try to enable wallbash first maybe you'll like it.
> 

My problem is font color.
Example Dolphin app and Alert Dialog, sidebar and breadcrumb color change to White (similar with background color), it's so hard to see and work with.
When no focus, color change to purple make it easier too see

**Comment by kRHYME7** [comment]
Oh, yes, Please open an issue here https://github.com/prasanthrangan/hyde-themes/tree/Catppuccin-Latte

And this is the file that needs to be modified  https://github.com/prasanthrangan/hyde-themes/blob/Catppuccin-Latte/Configs/.config/hyde/themes/Catppuccin%20Latte/kvantum/kvconfig.theme .


Please close the issue here and open it there. 

You can check out other themes too https://github.com/kRHYME7/hyde-gallery  or running ` Hyde theme patch `

**Comment by hoanggbao00** [comment]
> Oh, yes, Please open an issue here https://github.com/prasanthrangan/hyde-themes/tree/Catppuccin-Latte
> 
> And this is the file that needs to be modified  https://github.com/prasanthrangan/hyde-themes/blob/Catppuccin-Latte/Configs/.config/hyde/themes/Catppuccin%20Latte/kvantum/kvconfig.theme .
> 
> 
> Please close the issue here and open it there. 
> 
> You can check out other themes too https://github.com/kRHYME7/hyde-gallery  or running ` Hyde theme patch `  

nice, thank you so much
