### ISSUE TITLE
[Bug]: Waybar Bluetooth & Wifi Icons Unthemed?

### ISSUE THREAD

**Issue by Axhyy** [prasanthrangan/hyprdots#1537]
### Description

Waybar NetworkManager & blueman-manager icons unthemed after editing waybar dots

### Steps to Reproduce

1. Apply my editted waybar dots
[config.jsonc](https://github.com/prasanthrangan/hyprdots/files/15412857/config.jsonc)

### Expected Behavior

They should remain themed as usual

### Actual Behavior

They reverted back to what I assume to be the original icons, this happened right after applying my waybar dots and even after reapplying the hyprdots waybar dots they don't return back to normal.

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/113496361/602fdae6-08fb-48c5-8703-808ee8727d3c)

### Environment

- Linux Distro: EndeavourOS
- Linux Version, output of `uname -a`: Linux ArchG14 6.9.0-arch1-1.2-g14 #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 06:18:37 +0000 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`:  Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606
- Installation Environment: Main hardware
- Other info: N/A

Waybar dots that caused the issue:
[waybar.tar.gz](https://github.com/prasanthrangan/hyprdots/files/15412883/waybar.tar.gz)

**Comment by kRHYME7** [comment]
That's an expected behavior. We call it  Tray icons, they are dictated by the application running and rendered by the specific icon pack.  They can't be modified unless you modify the current Icon pack. This is not waybar related thing.

In example, these tray icons are from specific Icon-pack. 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/1e9e8b1f-361c-4717-a524-92256931e69c)


Example, this one is broken. 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/28147d45-1d75-4b9e-85a9-cc2f49663097)

**Comment by kRHYME7** [comment]
You can report a missing icon pack by visiting this and see who is the owner of the theme and report to their repo. 

https://github.com/kRHYME7/hyde-gallery?tab=readme-ov-file#theme-list
