### ISSUE TITLE
[Bug]: Spotify dock icon shows as ?

### ISSUE THREAD

**Issue by ritamgh** [prasanthrangan/hyprdots#1562]
### Description

Spotify icon in tray shows properly, but the one in dock shows as a ? in a white box, which I'm assuming is because it can't find the file with the spotify logo.

### Steps to Reproduce

Simply install spotify and this is what happens

### Screenshots

![image](https://github.com/prasanthrangan/hyprdots/assets/33598306/fce9f067-1824-48eb-8482-e317afb80b90)

### Environment

I recently installed Arch Linux on minimal, cloned this repo and installed the latest version of these dotfiles.

### Additional Information

Very new to arch, might just be a simple fix but I have no idea what to do rn. Tried a bunch of googling abt this issue, still got no clue. Sorry and thx for the help!

**Comment by kRHYME7** [comment]
@ignAtom  We can consider this as upstream bug so please checkout their repo https://github.com/spicetify/cli 

so at first you manually launch Spotify, underthehood it runs this command` spotify `. Now  because we love theming spotify we use ` spicetify-cli ` to theme it and let it handle the Spotify instance for us, this command is invoked while changing wallpapers  ` spicetify -q watch -s `. 

Now I do not know why spicetify-cli reports a ` null `  class so waybar (the taskbar)  do not know what is the icon so it just displays `  ? ` 

![Uploading image.png…]()

In hyprland you can query this by invoking ` hyprctl clients ` 


Will  close this for now. 


This is how the dynamic theming works on ` HyDE `  

 https://discord.com/channels/1200448076620501063/1231902035071471686/1234359467152379924
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/8c55e5ef-ab97-4cb1-b784-434e59d26c19)

**Comment by retubo** [comment]
Hi, I'm having the same issue.
I think that this is caused because the name of the app changes when using Spicetify to "Spotify Free" so the icons don't recognize this app:

![imagen](https://github.com/user-attachments/assets/f583c0bb-cb94-4d4f-b685-0c6c7757f14d)

In windows I had an option inside the spicetify config to change the name back to Spotify but I can't find it in linux. Maybe someone finds the solution

**Comment by kRHYME7** [comment]
Using `hyorctl clients ` command, The class is blank in my end. And the `title` of the window is actually the title of the song/music played. So there is no way the bar can recognize it.


Lemme check again the documentation if spictify-cli is capable of modifying the class name for Spotify

**Comment by retubo** [comment]
Hi, I found that if you delete the file with the flags it works fine. In my case I just changed the name:
![image](https://github.com/user-attachments/assets/3e5d4974-f43a-4ba9-b83f-514928976417)

**Comment by kRHYME7** [comment]
@retubo  Hi deleting this file will result in Spotify launching as Xwayland.

**Comment by MattyPixels** [comment]
This is indeed an upstream issue.
They're seemingly already fixed it and it will drop in the next release: https://community.spotify.com/t5/Desktop-Linux/Wayland-window-class-is-null/td-p/5591103

**Comment by abenezerw** [comment]
If this was fixed in said upstream issue can you please close this. @ritamgh

**Comment by ritamgh** [comment]
> If this was fixed in said upstream issue can you please close this. @ritamgh 

The fix has not been released as of now. I will close the issue whenever it gets released.

**Comment by kRHYME7** [comment]
Fixed on latest updates
![Uploading image.png…]()
