### ISSUE TITLE
[Bug]: Cursor is blurry on some apps but not others

### ISSUE THREAD

**Issue by Josh-Liddell** [prasanthrangan/hyprdots#1684]
Used [this](https://wiki.hyprland.org/Configuring/XWayland/) to properly adjust scale on my 4k monitor to 2 and can change size of cursor no problem however cursor becomes blurry when hovering over certain apps? Apps such as spotify, blender, pycharm, and more. Cursor is clear in firefox, kitty, thunar, libreoffice, etc. Something to do with whether the app is native wayland or not? I am struggling to find the solution to this issue and if it has something to do with the theming or not. Before changing the scale to 2 under monitors config, the cursor is not blurry just too small.

**Comment by kRHYME7** [comment]
just Xcursor not scaling. Specially when app is running over Xwayland. 

Apps that follows hyprcursor will scale while cursors that only follows gtk Xcursors will blurr when scaled. 

Note Try to use themes with Bibata-Modern-Ice cursor and see if some apps are blurry. 

` hyprctl  clients ` to know which windows are over xwayland

**Comment by kRHYME7** [comment]
@Josh-Liddell  When you run this ` ls ~/.icons/Bibata-Modern-Ice/ `  Do have the same output? 

![image](https://github.com/user-attachments/assets/d4456bf7-88b5-4a0f-bc68-bc121825b26e)

**Comment by Josh-Liddell** [comment]
@kRHYME7 My output does not include the hyprcursors directory or the manifest.hl could that be part of the issue? It does seem that the blurry cursor is only on the apps with Xwayland . The only workaround I have found is to keep overall scale at 1 but double the cursor size and scale apps individually to prevent the xcursor from being scaled up but this method is not preferred.

**Comment by kRHYME7** [comment]
@Josh-Liddell  


Check this out https://github.com/prasanthrangan/hyprdots/pull/1497 

Download extract that tarball to ` ~/.icons  ` 

Or overwrite ` ~/.icons/Bibata-Modern-Ice/ ` 
It should give you scalable cursor on some apps that are not using Xcursor.


But take note this is not the case for xwayland apps.  Because this is a wayland WM then we are emulating an environment for X11 apps that do not have the ability to scale.   
![image](https://github.com/user-attachments/assets/d7fdcbe8-ef71-4d2e-ba45-5d672ba80ca0)
