### ISSUE TITLE
[Feature Request]: Add polkit application for apps like gparted

### ISSUE THREAD

**Issue by FravkingTheCoder** [prasanthrangan/hyprdots#1733]
### Description

Add a polkit application like lxsession or kde-polkit for apps that require elevation

### Use Case

It's important to add and most people would get confused for apps like gparted not launching. Since this is a setup from the ground up its important to include it

### Proposed Solution

Add an polkit app like kde-polkit or lxsession

**Comment by kRHYME7** [comment]
polkit-kde-agent broke when kde moved to 6. the reason why the repo uses  polkit-gnome.  It should be installed now. I think the issue is gparted here. Sometimes It is not calling the polkit or the wayland toward gparted issue. 

You can run ` pkexec ` to see what polkit will pop up
![image](https://github.com/user-attachments/assets/eddfdf10-fae9-427b-abad-1930ac92fb4c)
