### ISSUE TITLE
[Bug]: Stuck on login screen loop

### ISSUE THREAD

**Issue by Kingmtu** [prasanthrangan/hyprdots#1748]
### Description

I installed hyprland using this script with minimal install I installed nvidia graphics with no flatpacks. After install everything works fine after I reboot the system. It stuck on login screen loop. I tried to login with CLI but hyprland won't start.
### Expected Behavior
I expect to login and use hyprland

### Actual Behaviour 
Stuck on login loop after I entered the password again then again login screen then went on.

### Screenshots
Not necessary 
### Environment
[Arch Linux]

**Comment by aniketkotal** [comment]
I'm not sure what the shortcut is but try `Ctrl` + `Alt` + `F2`/`F5`/`F7`. This will take you to a terminal where you can login. Once logged in, try running `Hyprland`. If it doesn't start, you'll get a bunch of logs. Have a look through, you might find something.

**Comment by Kingmtu** [comment]
![2024-08-14 15-50.jpg](https://github.com/user-attachments/assets/d29ac8a1-f990-49de-a4ca-5920c71cc812)

I got this via terminal

**Comment by dieBakterie** [comment]
We need the ones with error messages not just basic logs mate to help yo

**Comment by kRHYME7** [comment]
![image](https://github.com/user-attachments/assets/4ba6fdff-9a77-4783-a15e-8dd35ab7bfd8)
 Send logs to hyprland github maybe ?

**Comment by Kingmtu** [comment]
I'm getting this same screen when I run.  
 cat $XDG_RUNTIME_DIR/hypr/$(ls -t $XDG_RUNTIME_DIR/hypr | head -n 1)/hyprland.log

**Comment by Da4ndo** [comment]
Same issue, I just updated, than I got login loop.

**Comment by Kingmtu** [comment]
Before update your hyprland working?

**Comment by Da4ndo** [comment]
## Found the issue for me (no solution)

My hyprland worked perfectly; I updated the packages and used `Hyde upgrade` to update the dot files. Then I used my app Hyde-Ext to restore my configs from old dots. **Affected files:** userprefs.conf, monitors.conf, and.zshrc.
> It does not rewrite the file, but rather appends specific configurations to the files.  

After rebooting, I encountered a login loop with Hypland black screen freeze. I entered tty by using `ctrl + alt + F3` (or `fn + F3` for me). Then I forcibly upgraded to clean dots via `Hyde upgrade` (with overwrite all files) again and started Hyprland with `Hyprland`, which worked. Then I started manually restoring my configurations. First .zshrc, nothing, **then monitors.conf, which immediately froze the screen and required a forced shutdown of the computer, before looping again.**

It was also strange because it did not automatically detect my monitors when I started Hyprland. **So, in my opinion, it cannot identify the monitors, and including that configuration causes Hyprland to fail. This is a serious error that requires an immediate correction.** @prasanthrangan 

Information about setup:
- Lenovo laptop 
- Two LG monitors.

**Comment by Da4ndo** [comment]
Also, no matter what I do, I can't seem to connect my displays to my laptop anymore; I need help ASAP; I can't work like this.

**Comment by kRHYME7** [comment]
Hey, This is due to version 0.42.0 of hyprland.. The whole backend stuff is moved to aquamarine (from wlroots). I have the same issue where I can't render my 3rd monitor.

You can choose to downgrade by using the downgrade command.

**Comment by Kingmtu** [comment]
The issue seems to be fixed with the fresh install of hyprland at least for me. I'm using different dotfiles.

**Comment by xtirian** [comment]
> I'm not sure what the shortcut is but try `Ctrl` + `Alt` + `F2`/`F3`/`F7`. This will take you to a terminal where you can login. Once logged in, try running `Hyprland`. If it doesn't start, you'll get a bunch of logs. Have a look through, you might find something.

Thank you. Thais worked for me.
