### ISSUE TITLE
[Bug]: Waybar clock

### ISSUE THREAD

**Issue by TheyCallMeSecond** [prasanthrangan/hyprdots#1817]
now we have problem with waybar clock, clock showing UTC timezone instead of local time zone
its because tzdata package update
you can downgrade tzdata to 2024a-2 version to temporary fix the issue

**Comment by JaredKIso** [comment]
I appreciate this, I was just trying to figure out what was going on with that. Was driving me crazy

**Comment by pratyushkashyyy** [comment]
any idea on how to degrade or any steps ?

**Comment by sharjeelmazhar** [comment]
> now we have problem with waybar clock, clock showing UTC timezone instead of local time zone its because tzdata package update you can downgrade tzdata to 2024a-2 version to temporary fix the issue

what's the process/command to downgrade it? could you please help me out, i am new to arch linux

**Comment by sharjeelmazhar** [comment]
> now we have problem with waybar clock, clock showing UTC timezone instead of local time zone its because tzdata package update you can downgrade tzdata to 2024a-2 version to temporary fix the issue


@TheyCallMeSecond what's the process/command to downgrade it? could you please help me out, i am new to arch linux

**Comment by sharjeelmazhar** [comment]
### Solution to Downgrade `tzdata` Package

To resolve the issue with the Waybar clock showing the wrong timezone, you can downgrade the `tzdata` package to version `2024a-2`. Follow these steps:

1. Install the `downgrade` tool using your AUR helper (`paru` or `yay`):

    ```bash
    paru -S downgrade
    ```

    or

    ```bash
    yay -S downgrade
    ```

2. Use the `downgrade` tool to select and install the specific version of `tzdata`:

    ```bash
    sudo downgrade tzdata
    ```

3. From the list, select version **2024a-2**. This will downgrade the package.

4. After the downgrade, the system will ask if you'd like to add `tzdata` to the **ignore list** in the Pacman configuration (`/etc/pacman.conf`). This will prevent `tzdata` from being upgraded the next time you run:

    ```bash
    sudo pacman -Syu
    ```

    - Press `Y` and hit Enter to add `tzdata` to the ignore list. 

5. Once the bug is fixed upstream, you can remove `tzdata` from the ignore list by editing the `pacman.conf` file, and it will be upgraded automatically with your next system update.

---

I hope this helps!

**Comment by kRHYME7** [comment]
> you can remove tzdata from the ignore list by editing the pacman.conf file,

or running `yay -Sy tzdata` this command remove the package from the pacman.conf.

**Comment by sharjeelmazhar** [comment]
> `yay -Sy tzdata`
 will running this remove tzdata from the ignore package variable inside the conf file or will it ignore it for this specific command on the time we run this specific command with tag `-Sy` ?

**Comment by kRHYME7** [comment]
it removes it.

I tried this on dolphin last time.

**Comment by thyeun** [comment]
Recently most use command is ```dowgrade```.

**Comment by thyeun** [comment]
Hi All, update ```gcc``` to latest version will solve this issue.

**Comment by rubiin** [comment]
@kRHYME7 can be marked as solved
