### ISSUE TITLE
Waybar takes forever to start.

### ISSUE THREAD

**Issue by hqrakiri** [prasanthrangan/hyprdots#198]
Whenever I login it takes waybar around 30 seconds to show up? I thought this was my HDD so i moved arch to my much faster SSD and the issue still persists

**Comment by T-Crypt** [comment]
@kronikpillow beat me to it ^^^

**Comment by hqrakiri** [comment]
> Only reason why that ever would happen, is if your using another desktop or WM next to Hyprland, the Hyprland-xdg-portal is not compatible with others ... aka Hyprland can't be used in a multi wm or multi desktop environment, waybar launches completely fine for me

I installed arch linux and installed this. No other desktop environments or WM's

**Comment by T-Crypt** [comment]
What are your system specs?

**Comment by hqrakiri** [comment]
It's definitely not my system 
CPU: Ryzen 5 5600X
GPU: RX 580 (8GB Edition)
SSD: Gen3 M.2 NVMe

**Comment by prasanthrangan** [comment]
Is it just waybar that's slow to start? if so, please try running it from terminal, to check f there is any errors.

**Comment by kronikpillow** [comment]
Hm, now aftet finishing installation i have the same issue, i didnt have this issue yesterday before i wipped my ssd ... Wtf ...

AMD Radeon R9 380 graphics card ...

But this is the first time im using vaapi only drivers instead of having installed both vaapi and vdpau ... Now in wondering wtf

**Comment by kronikpillow** [comment]
Figured it out, i know this is not a proper way to send screenshots, but my system is not fully setup yet the way i like it (ironically i wipped my data hdd by mistake today, and now need to go trough struggle of retrieving all my passwords and data somehow ...

![IMG_20230913_093813.jpg](https://github.com/prasanthrangan/hyprdots/assets/48420193/e0aaff98-c487-4977-9696-52d9dee566f5)

Seems that the latest commits broke more then just exa, but i found a workaround ... Press MOD+ALT+Arrow Up to change the bar style, once you do, waybar will launch properly and won't but out anymore ...

Another thing i noticed breaks is during installation, if user goes AFK and doesnt enter password on each password prompt, packages fail to build ... One way to work around this is to use the sudo loop feature of yay (dunno if paru has the same), it will basically ask the user 1 time for the password, and thats it

**Comment by T-Crypt** [comment]
@prasanthrangan rather have frequent commits than dormant dotfiles!! we appreciate you .

**Comment by Manicpressure** [comment]
> Whenever I login it takes waybar around 30 seconds to show up? I thought this was my HDD so i moved arch to my much faster SSD and the issue still persists

Hey brah

I just solved this problem on my computer. I used to take around 25 seconds for waybar to start up, and another 15 seconds for firefox to launch.
`journalctl -xe`
Get to the bottom closer to the time where you logged in and started the loading process. Look for big time skips and if there are any processes where there were large gaps in time. THat will be the process you need to solve.

For me it was xdg-portal-desktop-gnome. It was failing because of 'dependency' - I dont know what it was, it just said 'dependency'. It was already updated so I tried uninstalling it. After uninstall the load time was lightning quick, as in, it just loads up with waybar open and I can super+f to open firefox straight away. 

Hope this helps.

**Comment by prasanthrangan** [comment]
Hey thank you so much for digging in bro!
I think I'll remove `xdg-portal-desktop-gnome` from the package list it seems to be causing issues with some applications... but it also would cause some applications (that access this portal) to fail...

**Comment by kRHYME7** [comment]
Be closing this and add this as a good first issue for referencing 

Conclusion: 

##### waybar takes time to load, 

+ After a fresh install toggle your waybar layout next/prev so that the waybar configuration will refresh/reset. 
+ https://github.com/prasanthrangan/hyprdots/issues/198#issuecomment-1719820486 You have another xdg-desktop-portal running. Removing or disabling this might help.

#### Helpful solutions too:

https://github.com/prasanthrangan/hyprdots/issues/198#issuecomment-1716345265
https://github.com/prasanthrangan/hyprdots/issues/198#issuecomment-1717112228
