### ISSUE TITLE
Browse local files in Steam open Visual Studio Code 

### ISSUE THREAD

**Issue by amedeo** [prasanthrangan/hyprdots#22]
How can I change the configuration so that when I choose "Browse local files" in Steam, Dolphin is launched instead of Visual Source Code?

**Comment by prasanthrangan** [comment]
Hi, I think the latest steam client uses `xdg-desktop-portal-gtk` for file picker, so are you referring to this -

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/725763df-0a3e-41c5-96d2-4bbfe2a3bed6)

I'm not sure why steam would use dolphin or vs code to browse local files.

**Comment by amedeo** [comment]
When attempting to browse for non-Steam games in the "Add Non-Steam Game" feature, nothing happens. Unlike the example you provided, I don't see a file manager. 
Instead, when I try to browse local files, 

![image](https://github.com/prasanthrangan/hyprdots/assets/8573/50276afb-9394-4e40-a988-4daf9f424995)

it opens VSCode. I suspect that there is a misconfiguration somewhere, but I'm unsure where to look for the solution. Thanks!

**Comment by prasanthrangan** [comment]
> When attempting to browse for non-Steam games in the "Add Non-Steam Game" feature, nothing happens. Unlike the example you provided, I don't see a file manager.

This is most likely due to `xdg-desktop-portal-gtk` package missing in your system, so please try it again after installing it and rebooting your system. I've also fixed this by adding this package to the install script. 


> it opens VSCode. I suspect that there is a misconfiguration somewhere, but I'm unsure where to look for the solution. Thanks!

it did open vs code for me as well, that was due to `code` set as default file explorer, please check `xdg-mime query default "inode/directory"` -

![image](https://github.com/prasanthrangan/hyprdots/assets/106020512/2f88b7fa-cb6f-4a40-ac35-40dee0e102e9)

you can fix it by updating the `/usr/share/applications/mimeinfo.cache` file. but this looks like a cache file, so i'll check how to set Dolphin as the system wide default.

**Comment by amedeo** [comment]
Awesome! I managed to fix it with:

`xdg-mime default org.kde.dolphin.desktop inode/directory`

Thanks

**Comment by prasanthrangan** [comment]
fixed in commit 56332bb
