### ISSUE TITLE
browser

### ISSUE THREAD

**Issue by cupenk** [prasanthrangan/hyprdots#437]
https://github.com/prasanthrangan/hyprdots/assets/29496587/ce4aba26-a7fd-47b2-868d-482c56993bdb

https://github.com/prasanthrangan/hyprdots/assets/29496587/acafa060-cafd-443b-9821-9ba0e68e52f8

 I'm using thorium, why aren't my bookmarks showing up?

**Comment by kRHYME7** [comment]
I think

Hi You are using your thorium browser on the x11 /xwayland session
I'm using Brave since both are Chromium base browsers to replicate your error.
Brave on x11 / xwayland:
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/a0efb490-cf8e-4848-a270-e7d1227b356c)

Then here is Brave on Wayland:
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/6cd67bab-56c2-4e58-a1fb-55455ddf77d4)

and this is Thorium on Wayland:
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/174704d4-a61d-4469-9e50-3db7d4c4321b)

Add here's the version comparison of both.
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/4df6d2b1-b01e-402d-b62d-e448174ba601)


I'm using thorium too.  Maybe we can raise this issue on Thorium? 


 (maybe someone out there has a better solution.

**Comment by kRHYME7** [comment]
Also can't we try not to raise issues that are not related to the repos configs? 
Someone is still willing to answer some issues here but this would clutter around. Also more importantly issues for packages like this should be raised on issue tracker for the package itself, it would be helpful for the package. Cheers

**Comment by cupenk** [comment]
> Also can't we try not to raise issues that are not related to the repos configs? Someone are willing to answer some issues here but this would clutter around. Also more importantly issues for packages like this should be raised on issue tracker for the package itself, it would be helpful for the package. Cheers

Alright understood.
