### ISSUE TITLE
Issues with theming and wallpaper

### ISSUE THREAD

**Issue by MdotAmaan** [prasanthrangan/hyprdots#5]
Hey o/ 
I just tried installing your dots on a fresh arch install, but noticed some issues.

- The wallpaper is stuck on the default Hyprland one. Doesn't appear to change when i hit the switch mode button. Speaking of,
- Pressing the switch mode button in waybar does not appear to do anything.
- One of the "pills" in waybar seems to be cut off from one side
![image](https://user-images.githubusercontent.com/38326222/235328249-e1e2d623-0fdc-4c6e-b81b-5eb5193b1719.png)
- The theming in general appears to be off. I'm not sure where exactly it's going wrong. Might have something to do with the mode switching thing. Here's dolphin as an example
![swappy-20230429_183927](https://user-images.githubusercontent.com/38326222/235328394-e331593f-9311-461f-8e19-7d17a822dda0.png)
mple 
- The install script doesn't work if you don't use grub. I just removed the grub portion from one of the scripts and that solved it though.

If there are any logs that might help do let me know ^^

**Comment by akashgagda** [comment]
I also use but there is no wallpaper issue for me working fine

**Comment by prasanthrangan** [comment]
Hey @MdotAmaan 

All these are related to the wallpaper script.
So please check if swww is running without errors, by running the script manually -

```
cd ~/.config/swww
./swwwallpaper.sh
```
this could be same as #3 

regarding, install script, it needs grub to enable nvidia drm.

**Comment by MdotAmaan** [comment]
The swww script was returning "ERROR: wallpaper link is broken". I tried re-running the install script and it appears to work properly now, along with all of the other configs. I'm not sure what went wrong the first time.

**Comment by prasanthrangan** [comment]
Cool thank you, it might be the symlink to the wallpaper that broke, or the wallpaper currently in use is missing/deleted.

**Comment by ScoptOriginal** [comment]
Just wanted to add on to this because it helped me with something else. The wallpapers are located at .config/swww/[your-theme-here] and you can dump any wallpapers you want to be able to use with each theme in the folder, and be able to use them exactly the same as any of the default wallpapers after the computer spends a short amount of time preparing them for use. I hope my comment can help more people who are looking for the same thing I was.

Now I just need to figure out how to get it to cycle through randomly :P
