### ISSUE TITLE
Power Mode & Screen Record

### ISSUE THREAD

**Issue by ArchBin** [prasanthrangan/hyprdots#506]
Hello Developer, Good Morning/Evening

im new user, can you help me to find screen record? Or theres no screen record? if there is no screen record here can you help me how to download it?

and how does it have a power mode, I noticed that my battery was draining fast.

Thank youu.

**Comment by kRHYME7** [comment]
Hi! Both of these are not yet implemented as there is no assurance that these packages work on every device.

These are my recommendations for Screen Recording:
https://github.com/russelltg/wl-screenrec
https://github.com/ammen99/wf-recorder
I would recommend using the wl-screenrec first to see if it works.  I am planning to implement this BTW soon. 


On Power mode: The Owner of the repo (I think is  using a Desktop Computer ):
As for Power Mode I recommend checking the Arch wiki https://wiki.archlinux.org/title/laptop. Also Check out TLP or Auto CPU freq. 
https://github.com/AdnanHodzic/auto-cpufreq  << I will Recommend you this 
https://wiki.archlinux.org/title/TLP

As for the implementation for these are really possible but may cause errors on not compatible devices. 

Please I would really recommend checking their websites first because the guides there are very useful. Do not hesistate to Ask questions if you have some problems. 

Some Contributor, 
Khing

**Comment by Zenbin-bash** [comment]
> Hi! Both of these are not yet implemented as there is no assurance that these packages work on every device.
> 
> These are my recommendations for Screen Recording: https://github.com/russelltg/wl-screenrec https://github.com/ammen99/wf-recorder I would recommend using the wl-screenrec first to see if it works. I am planning to implement this BTW soon.
> 
> On Power mode: The Owner of the repo (I think is using a Desktop Computer ): As for Power Mode I recommend checking the Arch wiki https://wiki.archlinux.org/title/laptop. Also Check out TLP or Auto CPU freq. https://github.com/AdnanHodzic/auto-cpufreq << I will Recommend you this https://wiki.archlinux.org/title/TLP
> 
> As for the implementation for these are really possible but may cause errors on not compatible devices.
> 
> Please I would really recommend checking their websites first because the guides there are very useful. Do not hesistate to Ask questions if you have some problems.
> 
> Some Contributor, Khing

Thank you for recommendation bro

I just have a question again, how to add a wallpaper and how to configure the chrome and vs code for transparency, I updated because my vs-code and suddenly the transparency disappeared

**Comment by kRHYME7** [comment]
You're welcome, brother.  
This is a frequently asked question would you mind checking issues #400 and #440,  instructions are available there.  Tell us what you find confusing.

**Comment by T-Crypt** [comment]
@Zenbin-bash 

To change chrome and code opacity you need to edit the window rules in `~/.config/hypr/windowrules.conf`

```
windowrulev2 = opacity 0.80 0.80,class:^(Code)$
windowrulev2 = opacity 0.80 0.80,class:^(chromium)$
```

**Comment by Zenbin-bash** [comment]
> @Zenbin-bash 
> 
> To change chrome and code opacity you need to edit the window rules in `~/.config/hypr/windowrules.conf`
> 
> ```
> windowrulev2 = opacity 0.80 0.80,class:^(Code)$
> windowrulev2 = opacity 0.80 0.80,class:^(chromium)$
> ```

Im not using chromium bro

**Comment by T-Crypt** [comment]
You would just replace chromium with your browser bro.

**Comment by prasanthrangan** [comment]
closing this as the issue seems to be resolved!
