### ISSUE TITLE
请问$mainmod ➕ A快捷键的rofi没有反应怎么办？

### ISSUE THREAD

**Issue by djjjs22** [prasanthrangan/hyprdots#523]
应用启动器启动不了 直接执行了rofilaunch.sh脚本也不行 报错failed  set to locale 但是我全局改回了英文还是不行

**Comment by kRHYME7** [comment]
If  ``` ~/.config/hypr/scripts/rofilaunch.sh ``` is not working, can we have a screenshot or the terminal output of the error?

**Comment by djjjs22** [comment]
对不起 原谅我实在不会用您的配置的截图快捷键 只能用手机拍了
![Uploading IMG_20231119_083118.jpg…]()
![Uploading IMG_20231119_082146.jpg…]()
其他的脚本也运行不了

**Comment by kRHYME7** [comment]
It is fine, no worries, can you re-upload the images?  We cannot open it.

>Uploading IMG_20231119_083118.jpg…
Uploading IMG_20231119_082146.jpg…

**Comment by djjjs22** [comment]
https://ooo.0x0.ooo/2023/11/19/OrMUPG.jpg
https://ooo.0x0.ooo/2023/11/19/OrMW91.jpg
我重新上传了。麻烦您看一下

**Comment by OctavianOG** [comment]
Greetings @djjjs22 , there shouldn't be any problem with rofilaunch, as stated in the rofi error: `Failed to set locale`, so the error is only with locales. There could be many reasons why this error occurs, but we'll look at the most common one.

Could you check please, does the locale-gen file contain `en_US.UTF-8 UTF-8` in it, because it might be just `en_US.UTF-8` without additional UTF-8?

To do so, you need to:
1. Enter locale-gen file (I'll use nano to do so)
```ruby
sudo nano /etc/locale.gen
```
2. Find `en_US.UTF-8 UTF-8` line, it should be uncommented, i.e. without #(if it's not, then do so) and contain additional UTF-8 part
3. If the line only says `en_US.UTF-8` without additional UTF-8 part, exit text-editor you're using
4. Run this command:
```ruby
sudo echo en_US.UTF-8 UTF-8 > /etc/locale.gen && locale-gen
```

Everything should work now, if not I'm willing to provide further troubleshooting assistance.

> [!TIP]
>If you want to get more info about Arch Linux locale here's the [wiki](https://wiki.archlinux.org/title/Locale)

**Comment by djjjs22** [comment]
请你看看是这样吗？https://ooo.0x0.ooo/2023/11/20/OrTAnF.jpg
https://ooo.0x0.ooo/2023/11/20/OrTK46.jpg
操作跟着您说的去做了，但看样子好像还是不行

**Comment by OctavianOG** [comment]
@djjjs22 , could you please provide output of the following commands:
```ruby
locale -a
```
```ruby
localectl
```
```ruby
grep -v ^# /etc/locale.gen
```

**Comment by djjjs22** [comment]
https://ooo.0x0.ooo/2023/11/20/OrbGk6.jpg请问是这样吗？ 其实是有三个问题的，缩放问题跟设置中文的 中文怎么改都不行但影响不大 缩放问题自己解决了 但是这个应用启动器怎么弄都不行 还有那个主题跟壁纸菜单栏切换都不行 都是failed set to locale

**Comment by OctavianOG** [comment]
@djjjs22 , could you please try and provide output of this alternative commands:
```ruby
grep -v \^# /etc/locale.gen
```
```ruby
grep -v '^#' /etc/locale.gen
```

**Comment by OctavianOG** [comment]
@djjjs22 , could you please run and provide output of this commands:
```ruby
sudo locale-gen
```
```ruby
locale -a
```
```ruby
localectl
```
```ruby
rofi -r
```

**Comment by djjjs22** [comment]
https://ooo.0x0.ooo/2023/11/20/Orb6pC.jpg   请问看出什么来了吗？

**Comment by OctavianOG** [comment]
@djjjs22 , i think i find the error, something changed your `LC_TIME` and `LC_MONETARY` to be `en_DK.UTF-8`

To resolve problem do this:
1. Run this command, to enable en_DK locale
```ruby
sudo sed -i '/en_DK.UTF-8/s/^#//g' /etc/locale.gen
```
2. After previous step, run this to rebuild locales again
```ruby
sudo locale-gen
```
3. Run following command to ensure that rofi working
```ruby
rofi -r
```

**Comment by djjjs22** [comment]
https://ooo.0x0.ooo/2023/11/20/OrktTL.jpg 很抱歉跟你想的不一样 还是不行

**Comment by OctavianOG** [comment]
@djjjs22 , sorry for confusion, `sudo sed -i '/en_DK.UTF-8/s/^#//g' /etc/locale.gen` - doesn't seem to work for you. Use manual way to enable `en_DK` locale.

To do so:
1. Open `/etc/locale.gen` file
```ruby
sudo nano /etc/locale.gen
```
2. Find line that contains `en_DK.UTF-8 UTF-8`, and uncomment it, it should be without `#`

After all of this, proceed with steps 2 and 3 from my previous reply:

> 
> 2. After previous step, run this to rebuild locales again
> 
> ```ruby
> sudo locale-gen
> ```
> 
> 3. Run following command to ensure that rofi working
> 
> ```ruby
> rofi -r
> ```

**Comment by katsuja** [comment]
> https://ooo.0x0.ooo/2023/11/19/OrMUPG.jpg https://ooo.0x0.ooo/2023/11/19/OrMW91.jpg 我重新上传了。麻烦您看一下

You have to run the script without sudo

**Comment by katsuja** [comment]
> https://ooo.0x0.ooo/2023/11/19/OrMUPG.jpg https://ooo.0x0.ooo/2023/11/19/OrMW91.jpg 我重新上传了。麻烦您看一下

Here it asks you to install jq:
paru -S jq

**Comment by kRHYME7** [comment]
Hi, @katsuja  Please refrain from running the shell scripts with sudo because it may cause errors/issues in the future. Also maybe not related to your problem but what is your keyboard layout? 


I also have questions for the community here, does setting our system to a different locale cause some issues on scripts? also if we set our locale to non-en_US.UTF-8(which is used in this repo) does this change the interpretation of some packages and scripts?

**Comment by OctavianOG** [comment]
@djjjs22 , so what was the solution to the problem?

**Comment by kRHYME7** [comment]
Nice! Sometimes reinstalling is way more convenient. We can close this issue now !

**Comment by prasanthrangan** [comment]
cool, looks like this is resolved!
