### ISSUE TITLE
Failed to create symbolic link : no such file or directory.

### ISSUE THREAD

**Issue by aitihya69** [prasanthrangan/hyprdots#540]
![IMG_20231123_031637.jpg](https://github.com/prasanthrangan/hyprdots/assets/75194999/e9114256-b226-4ae1-b809-a0cf8aed4dbb)

Having this error at the end. Can someone help please? Thanks!

**Comment by kRHYME7** [comment]
🧐, What happens if you re run the installation? do you still get these errors?

**Comment by aitihya69** [comment]
> Hi 🧐, What happens if you re run the installation? do you still get these errors?
I'm trying this on endeavourOs just as in the video that was linked in the GitHub page. 
I didn't reinstall the endeavourOs but just re-running the script gets me to the same error every time.

**Comment by kRHYME7** [comment]
Does the script exit if  that error occurs?

we can modify the part that gives errors  so that the scripts still continue to install these configs.

Are you comfortable modifying  the script? This is only a workaround though, the owner of the repo might be busy on weekdays he should have a better way to fix this.

**Comment by prasanthrangan** [comment]
Hi, looks like you have created a symlink within your clone dir `~/hyprdots` so please find it as below
```
find $HOME/hyprdots -type l 
```
then remove the one that links to wlogout tar file.

**Comment by kRHYME7** [comment]
Hey man, thanks I understand now how this linking works Haha.

**Comment by kRHYME7** [comment]
Feel free to reopen the issue incase you still experience this.
