### ISSUE TITLE
hyprland-nvidia-git not needed, I suggest using hyprland-git

### ISSUE THREAD

**Issue by nicolkrit999** [prasanthrangan/hyprdots#628]
Necessary patches are already included in the regular package

**Comment by kRHYME7** [comment]
Hi is the latest commit still tries to install hyprland-nvidia?

**Comment by Skerse** [comment]
If you're downloading hyprdots since this commit: https://github.com/prasanthrangan/hyprdots/commit/e5444e02d5908f5fe3744e416640917f0675ecb9 the script should no longer be installing hyprland-nvidia-git and only be installing hyprland-git.

If you were updating the dots overtime you may still need to manually change it but you just install hyprland-git, then pacman will ask you if you want to replace the hyprland-nvidia-git package, do it and you're done.
