### ISSUE TITLE
Install script way more invasive than i thought, messed up my main KDE DE and no idea how to revert

### ISSUE THREAD

**Issue by Nebzla** [prasanthrangan/hyprdots#630]
I'm slightly panicking right now, my KDE environment is in a mess and its plastered with all anime i dont want, things are themed weirdly, my konsole is messed up with pokemon, so is my grub bootloader, my themes are messed up, and its all in a completely unprofessional state and i need it reverted urgently, can anyone please help me? I cant find any sort of install script that can get rid of this stuff, and looking through all the related application settings i find nothing that indicates where this stuff even came from.

**Comment by Skerse** [comment]
There is nothing anyone can do about its "invasiveness" because it's changing your configs for the apps to fit with the dots theming, both KDE Plasma and Hyprland use the same configs for the same apps.

Now about reverting it all, as far as the configs go you can take what was backed up to ~/.config/cfg_backups and place all the files/folders back to where they used to go and that'll solve most of your desktop theming issues. Sddm can also be changed with KDE system settings. If your shell was not zsh that can be changed by doing chsh -s /path/to/shell. Grub is more difficult, but can maybe be changed back with [grub-customizer](https://archlinux.org/packages/extra/x86_64/grub-customizer). I hope that helps you.

**Comment by prasanthrangan** [comment]
Hi @Nebzla , this reeo shares a lot of config with KDE and it is expected..
Please find your backup configs in `~/.config/cfg_backups/*`, it follows the same file structure as your $HOME directory, so you can just copy and paste it to your home to revert the changes (of course excluding sddm and grub)

**Comment by Nebzla** [comment]
I will give that a go, thanks

**Comment by prasanthrangan** [comment]
@Skerse has already updated the readme to warn users about this, so i'll close this!
