### ISSUE TITLE
Floorp Help

### ISSUE THREAD

**Issue by Rafi1018** [prasanthrangan/hyprdots#693]
I'm interested on using Floorp (Firefox clone) instead of Firefox. But I was curious if using that will result in some artifacts or issues or not. I don't have enough bandwidth to experiment it on my own.
So will Floorp will be ok or should I stick to Firefox ?

Also anyway I can skip the Bluetooth & WiFi stuff as I use Ethernet & nothing related to Bluetooth

**Comment by theCode-Breaker** [comment]
@Rafi1018 
There should be no issues use whatever browser you want

**Comment by theCode-Breaker** [comment]
@Rafi1018 
There should be no issues use whatever browser you want

**Comment by Rafi1018** [comment]
> @Rafi1018 There should be no issues use whatever browser you want

Got it & what about disabling wifi & bluetooth stuff how can I skip them

**Comment by Rafi1018** [comment]
Also what is the game launcher based of.... like which app is it part of hyprland ?
Sorry a newbie here!

**Comment by Skerse** [comment]
> I'm interested on using Floorp (Firefox clone) instead of Firefox. But I was curious if using that will result in some artifacts or issues or not.

This will not cause any issues with theming as long as it takes from the gtk theme which it should.

> Got it & what about disabling wifi & bluetooth stuff how can I skip them?

If for whatever reason you want to disable wifi and bluetooth you can do: 
`sudo systemctl disable NetworkManager.service`
`sudo systemctl disable bluetooth.service`
To enable again you can replace disable with enable.

> Also what is the game launcher based of.... like which app is it part of hyprland?

It's using [rofi](https://archlinux.org/packages/extra/x86_64/rofi), since rofi is very customizable and works well. You can find the configs in `~/.config/rofi/steam`.

**Comment by Rafi1018** [comment]
got it thanks
