### ISSUE TITLE
Chrome error

### ISSUE THREAD

**Issue by PabloMartinMoreno** [prasanthrangan/hyprdots#719]
I installed Chrome and it has issues with transparency; besides, when I open certain extensions, it closes. In windowrules.conf, it doesn't appear with opacity; the only browser with opacity was Firefox, and I already removed it.

**Comment by kRHYME7** [comment]
Hmm, I guess you can add an opacity value for Chrome in your ```  ~/.config/hypr/userprefs.conf    ``` let as know what is the title or class for Chrome you can do that by running ``` hyprctl clients  ``` then find the client that indicates chrome get the class then add it like this ``` windowrulev2 = opacity 0.8 0.8,class:^(chrome)$ ``` on your ./userprefs.conf. 

Checking the https://wiki.hyprland.org/Configuring/Window-Rules/ should also work. 

>besides, when I open certain extensions, 

How often does the extension cause crashes? Is it caused by the extension? Chrome? Hyprdots? Hyprland? Wayland? Linux?

**Comment by dvsociety** [comment]
> Hmm, supongo que puedes añadir un valor de opacidad para Chrome en tu ` ~/.config/hypr/userprefs.conf `hacer tan saber cuál es el título o clase para Chrome se puede hacer que corrindo `hyprctl clients `entonces encontrar el cliente que indica cromo obtener la clase y luego añadirlo así `windowrulev2 = opacity 0.8 0.8,class:^(chrome)$`en su ./userprefs.conf.
> 
> También debería funcionar la [comprobación de https://wiki.hyprland.org/Configuring/Window-Rules/](https://wiki.hyprland.org/Configuring/Window-Rules/).
> 
> > Además, cuando abra ciertas extensiones,
> 
> Con qué frecuencia la extensión causa accidentes? Es causada por la extensión? Chrome? Hyprdots? Hyprland? Wayland? Linux?

As I mentioned earlier, the configuration in windowrules.conf doesn't change anything; I don't even have the line that sets opacity added. But if I add it and set it to not have it, it still gives the same error. It's practically impossible to use; any menu that I open for more than a few seconds causes it to close.

**Comment by kRHYME7** [comment]
@dvsociety Still got these errors on chrome? What package of chrome did you installed?
